name: campervan
description: "CamperVan Dashboard"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  html: ^0.15.4
  image: ^4.3.0
  # intl: ^0.19.0
  intl: ^0.20.2
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.3
  riverpod_annotation: ^2.6.1
  statistics: ^1.0.25
  fast_immutable_collections: ^11.0.4
  equatable: ^2.0.7
  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  web_socket_channel: ^3.0.3
  flutter_layout_grid: ^2.0.8

dev_dependencies:

  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.3
  objectbox_generator: any

flutter:

  uses-material-design: true

